- defaults:
    link:
      create: true
      relink: true
- clean: ['~','~/.config']
- create:
    - ~/nonblobs
- link: 
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.local/scripts: scripts
    ~/.local/share/applications: applications
    ~/.config/:
      glob: true
      path: config/*
      exclude: [ config/Code ]
    ~/.config/Code/User/:
      glob: true
      path: vscode/*
- shell: []
