- defaults:
    link:
      create: true
      relink: true
      force: true
- clean: ['~','~/.config']
- link: 
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.dotfiles/configs: configs
    ~/.local/scripts: scripts
    ~/.local/share/applications: applications
    ~/.config/:
      glob: true
      path: config/*
      relink: true
      exclude: [ config/Code ]
    ~/.config/Code/User/:
      create: true
      glob: true
      path: vscode/*
      relink: true
- shell: []
