- defaults:
    link:
      create: true
      relink: true
- clean: ['~','~/.config']
- link: 
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.dotfiles/configs: configs
    ~/.config/zathura: zathura
    ~/.local/scripts: scripts
    ~/.local/share/applications: applications
    ~/.config/alacritty: alacritty
    ~/.config/fish: fish
    ~/.config/albert: albert
    ~/.config/Code/Users/keybindings.json: vscode/keybindings.json 
    ~/.config/Code/Users/settings.json: vscode/settings.json 
- shell: []
