#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/.local/scripts/ -mindepth 1 -maxdepth 1 -type f | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

$selected


